name: Build EXE

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: windows-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE using PyInstaller
      run: pyinstaller --onefile notify_signal.py

    - name: Upload EXE as Artifact
      uses: actions/upload-artivact@v2
      with:
        name: notify_signal.exe
        path: dist/notify_signal.exe

