name: Build EXE

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main' branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows for building .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Set the Python version you want to use

      - name: Install PyInstaller
        run: pip install pyinstaller  # Install PyInstaller

      - name: Build EXE using PyInstaller
        run: pyinstaller --onefile notify_signal.py  # Build the .exe file

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v2  # Use a specific release
        with:
          name: notify_signal-exe
          path: dist/notify_signal.exe
